import type { Metadata } from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";

const dmsans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChatApps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmsans.variable} antialiased font-(--font-dm-sans)`}
      >
        {children}
      </body>
    </html>
  );
}
